# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_skydiver.ipynb.

# %% auto #0
__all__ = ['terminal_velocity', 'velocity_at_time', 'time_to_fraction']

# %% ../nbs/00_skydiver.ipynb #imports
import numpy as np

# %% ../nbs/00_skydiver.ipynb #terminal-velocity
def terminal_velocity(
    mass_kg: float,
    drag_coefficient: float,
    gravity: float = 9.81,
) -> float:
    """Return the magnitude of terminal velocity in meters per second."""
    if mass_kg <= 0 or drag_coefficient <= 0 or gravity <= 0:
        raise ValueError("mass, drag coefficient, and gravity must be positive")
    return float(np.sqrt(mass_kg * gravity / drag_coefficient))

# %% ../nbs/00_skydiver.ipynb #velocity
def velocity_at_time(
    time_s: float | np.ndarray,
    mass_kg: float,
    drag_coefficient: float,
    gravity: float = 9.81,
) -> float | np.ndarray:
    """Return downward velocity for a skydiver starting from rest."""
    if np.any(np.asarray(time_s) < 0):
        raise ValueError("time must be non-negative")
    limit = terminal_velocity(mass_kg, drag_coefficient, gravity)
    velocity = -limit * np.tanh(gravity * np.asarray(time_s) / limit)
    return float(velocity) if np.ndim(velocity) == 0 else velocity

# %% ../nbs/00_skydiver.ipynb #time-fraction
def time_to_fraction(
    fraction: float,
    mass_kg: float,
    drag_coefficient: float,
    gravity: float = 9.81,
) -> float:
    """Return seconds required to reach a fraction of terminal velocity."""
    if not 0 < fraction < 1:
        raise ValueError("fraction must be between 0 and 1")
    limit = terminal_velocity(mass_kg, drag_coefficient, gravity)
    return float(limit / gravity * np.arctanh(fraction))
