name: Test & Coverage

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  

jobs:
  test:
    if: contains(github.event.head_commit.message, 'RELEASE')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install full requirements except pywin32
        run: |
          grep -v "^pywin32" requirements.txt > req.txt
          python -m pip install --upgrade pip
          pip install -r req.txt
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests with coverage (fail under 75%)
        run: |
          pytest --cov=mnist_ae --cov-report=term --cov-report=xml --cov-fail-under=75

      - name: Sanitize commit message for branch name
        id: sanitize_message
        run: |
          # Sanitize the commit message to create a valid branch name
          BRANCH_NAME=$(echo "${{ github.event.head_commit.message }}" | sed -e 's/[^a-zA-Z0-9._-]/-/g' | cut -c1-50)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create a new release branch from develop
        run: |
          git checkout -b $BRANCH_NAME develop
          git push origin $BRANCH_NAME

      - name: Success message
        if: success()
        run: echo "Coverage ≥ 75 %. You can open a PR from develop to master."

